#!/bin/sh

set -e

case "$1" in
    configure)
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
	exit 0
	;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

. /usr/share/debconf/confmodule
db_version 2.0
db_get dpkg-www/update-apache-config

for server in apache2 apache apache-ssl; do
    apachectl="/usr/sbin/${server}ctl"
    apachepid="/var/run/${server}.pid"
    if [ -x $apachectl -a -f $apachepid ]; then
	echo "Restarting $server..." >&2
	$apachectl restart >&2 </dev/null || true
    fi
done

#DEBHELPER#
exit 0

# end of file
