#!/bin/sh
#
# Command-line interface to dpkg-www.
#
# Copyright © 1999-2006 Massimo Dal Zotto <dz@debian.org>
# Copyright © 2019-2022 Guillem Jover <guillem@debian.org>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

usage() {
    # Automatic help hack
    echo "Usage: ${0##*/} [<options...>] [<query>]"
    echo
    echo "Options:"
    echo
    sed '/^	-/!d; s/\\//; s/)//; s/#/</; s/#/>/' $0
    echo
}

urlencode() {
    perl -e '
        $s=join(" ",@ARGV);
        $s=~s/([^a-zA-Z0-9 _\.*@-])/uc sprintf("%%%02x",ord($1))/eg;
        $s=~s/ /+/g;
        print $s . "\n";'   "$*"
}

if [ -n "$DPKG_WWW_HOST" ]; then
    DPKG_WWW_URL="https://$DPKG_WWW_HOST/cgi-bin/dpkg"
else
    DPKG_WWW_URL="http://localhost/cgi-bin/dpkg"
fi
X11_BROWSERS="\
    sensible-browser x-www-browser
    chromium firefox konqueror falkon epiphany-browser midori
    dillo surf xlinks2"
TXT_BROWSERS="\
    sensible-browser www-browser
    elinks links2 links lynx w3m"

browser=
browser_args=
while [ "${1#-}" != "$1" ]; do
    case "$1" in
	-\?|-help|--help)
	    usage
	    exit
	    ;;
	-x|--xtrace)
	    shift 1
	    set -x
	    ;;
	-h|--host) #host#
	    test "$2" || { usage; exit 1; }
	    DPKG_WWW_URL="https://${2}/cgi-bin/dpkg"
	    shift 2 || exit 1
	    ;;
	-s|--stdout)
	    shift 1
	    export DISPLAY=""
	    noheader="&noheader=true"
	    if command -v lynx >/dev/null; then
		browser="lynx"
		browser_args="-dump -nolist"
	    elif command -v lynx-ssl >/dev/null; then
		browser="lynx"
		browser_args="-dump -nolist"
	    elif command -v links >/dev/null; then
		browser="links"
		browser_args=""
	    elif command -v w3m >/dev/null; then
		browser="w3m"
		browser_args=""
	    fi
	    ;;
 	--|*)
	    break
	    ;;
    esac
done

# Source optional local and user configuration files
test -e /etc/dpkg-www.conf && . /etc/dpkg-www.conf 2>/dev/null
test -e ~/.dpkg-www && . ~/.dpkg-www 2>/dev/null

if [ "$DISPLAY" ]; then
    for f in $browser $DPKG_WWW_BROWSER $X11_BROWSERS $TXT_BROWSERS; do
	if command -v $f >/dev/null 2>&1; then
	    browser=$f
	    break
	fi
    done
else
    for f in $browser $DPKG_WWW_BROWSER $TXT_BROWSERS; do
	echo $X11_BROWSERS | grep -qw "$f" && continue	# skip X11 $BROWSER
	if command -v $f >/dev/null 2>&1; then
	    browser=$f
	    break
	fi
    done
fi

if [ ! "$browser" ]; then
    echo "dpkg-www: no WWW browser found" >&2
    exit 1
fi

query=$(urlencode "$*")
if [ "$DEBUG" = 1 -o "$DEBUG" = true ]; then
    echo $browser $browser_args "$DPKG_WWW_URL?query=$query$noheader"
fi
exec $browser $browser_args "$DPKG_WWW_URL?query=$query$noheader"

# end of file
